-- Glossa · migración 0006 — recuperar la deriva de esquema
-- NO aplicada todavía. Es idempotente y NO destructiva: solo declara en el repo
-- dos tablas que YA existen en producción (creadas desde fuera de este repo,
-- probablemente desde `aauml/thesis`, para la vista Glossa del dashboard).
--
-- Motivo: `skills/SKILL.md` manda escribir `glossa_issue_targets`, y el dashboard
-- consume `glossa_candidates`, pero ninguna de las dos tenía migración aquí.
-- `db/migrations` había dejado de describir la base. Esto lo corrige.
--
-- Estado observado en wtwuvrtmadnlezkbesqp el 2026-08-20:
--   glossa_issue_targets: 14 filas · glossa_candidates: 10 filas
--
-- Nota de frontera: `glossa_issue_targets.work_slug` referencia `works(slug)`,
-- una tabla del dominio de la tesis. Es la única FK de Glossa que sale del
-- prefijo `glossa_*`; se declara aquí para dejarlo explícito, no para adoptarla.

create table if not exists public.glossa_issue_targets (
  id integer generated by default as identity primary key,
  issue_id uuid not null references public.glossa_issues(id) on delete cascade,
  work_slug text not null references public.works(slug),   -- tesis | art-ail-2027
  section_ref text,                                        -- subsección ("1.7") o seq del artículo ("3")
  created_at timestamptz not null default now(),
  unique (issue_id, work_slug, section_ref)
);
comment on table public.glossa_issue_targets is 'Glossa: a qué obra y sección sirve cada pieza. Alimenta la vista Glossa del dashboard (colección agrupada por capítulo -> sección) y el seguimiento.';

create table if not exists public.glossa_candidates (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null,
  chapter_num integer not null,
  section_num text,
  section_title text,
  title text not null,
  angle text not null,
  rationale text,
  source_pks uuid[] not null default '{}',
  sources jsonb not null default '[]',
  prompt text not null,
  status text not null default 'proposed'
    check (status in ('proposed', 'copied', 'discarded', 'published')),
  copied_at timestamptz,
  model text,
  created_at timestamptz not null default now(),
  work_slug text not null default 'tesis',
  article_seq integer
);
comment on table public.glossa_candidates is 'Glossa: propuestas de piezas por capítulo/inciso generadas por generate-glossa-candidates. Pre-seed: al copiar el prompt y ordenar la pieza en Claude se crea el glossa_seed (autoría humana). sources jsonb: [{pk,title,importance,used_in:[issue_no]}]. Regla: no repetir combinación exacta de source_pks; reutilizar fuentes individuales en mezclas nuevas es válido.';

create index if not exists idx_glossa_candidates_chapter on public.glossa_candidates (chapter_num, status, created_at desc);
create index if not exists idx_glossa_candidates_work    on public.glossa_candidates (work_slug, status);

alter table public.glossa_issue_targets enable row level security;
alter table public.glossa_candidates     enable row level security;
