// El prompt del cotejo. Aquí vive el criterio, así que se edita con el mismo
// cuidado que `supabase/functions/_shared/prompts.ts` — vive aparte porque este
// guion corre en Node y aquel es Deno.

export function promptCotejo(claim, item, hallazgo) {
  return [
    'A claim was made in a podcast or video. A web search returned one document.',
    'Decide what that document does to the claim.',
    '',
    'THE CLAIM:',
    `  "${claim.texto}"`,
    `  said by: ${(item.digest?.speakers ?? []).join(', ') || item.author || 'unnamed'}`,
    `  on: ${String(item.published_at).slice(0, 10)}`,
    `  the analyst noted it could be checked by: ${claim.checkable}`,
    claim.status ? `  recorded as: ${claim.status}` : '',
    '',
    'THE DOCUMENT:',
    `  title: ${hallazgo.title ?? '(none)'}`,
    `  site: ${hallazgo.source_domain}`,
    `  published: ${hallazgo.published_date ?? 'unknown'}`,
    `  text: ${String(hallazgo.snippet ?? '').slice(0, 4000)}`,
    '',
    'Return ONLY JSON:',
    '{"verdict":"documenta|repite|contradice|no_concluyente",',
    ' "reason":"one sentence, plain",',
    ' "independence":"independiente|misma_orbita|desconocida",',
    ' "documento":"the named record it points to, or null"}',
    '',
    'RULES — the first two are the ones that matter:',
    '',
    '- **documenta** ONLY if the page IS a record, or directly reproduces one — a',
    '  filing, a ruling, a dataset, an official release, a full transcript, a statute —',
    '  AND that record states the claim. **A journalist reporting a record is not the',
    '  record.** If you cannot name the record in `documento`, the verdict cannot be',
    '  `documenta`.',
    '',
    '- **repite** if the page says the same thing but is commentary, aggregation, or',
    '  traces back to the same origin as the claim. Say in `reason` where it traces to.',
    '  Several outlets carrying one wire story is one source, not four.',
    '',
    '- **contradice** is the most valuable verdict there is, which is exactly why it',
    '  must be earned. Use it ONLY when the document measures the SAME thing and gets',
    '  a materially different answer — a different figure for the same quantity on the',
    '  same date, a denial of the same event, a ruling the other way. A number that is',
    '  close but not identical, a figure from a different date, or a document about a',
    '  neighbouring subject is `no_concluyente`, not a contradiction. Say what part is',
    '  contradicted and what the document says instead.',
    '',
    '- **no_concluyente** when the document is about the same subject but does not',
    '  bear on this particular claim. That is a common and honest answer.',
    '',
    '- `independence`: `independiente` only if this document comes from a different',
    '  world than the speaker — different institution, different political home,',
    '  different incentives — and rests on its own evidence. Agreement between people',
    '  who share a school measures alignment, not confirmation. When in doubt,',
    '  `desconocida`.',
    '',
    '- Judge only what the text supports. You are not being asked whether the claim',
    '  is true; you are being asked what THIS document does to it.',
  ].filter(Boolean).join('\n');
}
